version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    network_mode: bridge
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo_user
      - MONGO_INITDB_ROOT_PASSWORD=mongo_pass
    volumes:
      - type: bind
        source: ./mongo
        target: /data/db
